---
apiVersion: v1
kind: Namespace
metadata:
  name: facebook
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: facebook
  labels:
    role: web-service
spec:
  containers:
  - name: nginx
    image: warriconnected/webapp:v1.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: facebook
  labels:
    role: web-service
spec:
  selector:
    role: web-service
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32001
